### PR TITLE
Feature/cg 1043

### PR DESCRIPTION
**Pull request by csbrandt**

### CODE REVIEW

**Comment by tyler-dunkel** [comment]
PR should be to alpha not main

**Comment by tyler-dunkel** [comment]
I see this doesnt have `replicationPolicies` and `replicationCenters` from the ticket discussion. Are we ok with not adding those?

**Comment by csbrandt** [comment]
> I see this doesnt have `replicationPolicies` and `replicationCenters` from the ticket discussion. Are we ok with not adding those?

I didnt want to make the pr too big, will add those other services as well.

**Comment by tyler-dunkel** [comment]
> > I see this doesnt have `replicationPolicies` and `replicationCenters` from the ticket discussion. Are we ok with not adding those?
> 
> I didnt want to make the pr too big, will add those other services as well.

sounds good 👍

**Review by tyler-dunkel — APPROVED** [review]

**Pull request merged**
