### PR TITLE
fix: replace cuid usage, remove conditional cuid generation for root ids

### PR DESCRIPTION
**Pull request by hjaraujof**
## Changes/solution

- Replace cuid generation with CG native generateUniqueId helper, to reduce entropy while generating ids

### CODE REVIEW

**Comment by tyler-dunkel** [comment]
For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?

**Comment by hjaraujof** [comment]
@tyler-dunkel > For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?

Yes, this will significantly reduce entropy and make most id "noise" disappear.

**Comment by tyler-dunkel** [comment]
> @tyler-dunkel > For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?
> 
> Yes, this will significantly reduce entropy and make most id "noise" disappear.

yea but arent we already "ignoring" ids with the noise changes we made app side?

**Comment by hjaraujof** [comment]
> > @tyler-dunkel > For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?
> > Yes, this will significantly reduce entropy and make most id "noise" disappear.
> 
> yea but arent we already "ignoring" ids with the noise changes we made app side?

No, we don't ignore ids because they play an important role when recognizing created/deleted data

**Comment by tyler-dunkel** [comment]
> > > @tyler-dunkel > For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?
> > > Yes, this will significantly reduce entropy and make most id "noise" disappear.
> > 
> > 
> > yea but arent we already "ignoring" ids with the noise changes we made app side?
> 
> No, we don't ignore ids because they play an important role when recognizing created/deleted data

not ids from the provider, ids that are generated. i.e. ids from nested objs

**Review by tyler-dunkel — APPROVED** [review]

**Comment by hjaraujof** [comment]
> > > > @tyler-dunkel > For snapshot diff, do we ignore ids with the latest changes or is this change still necessary to avoid that "noise"?
> > > > Yes, this will significantly reduce entropy and make most id "noise" disappear.
> > > 
> > > 
> > > yea but arent we already "ignoring" ids with the noise changes we made app side?
> > 
> > 
> > No, we don't ignore ids because they play an important role when recognizing created/deleted data
> 
> not ids from the provider, ids that are generated. i.e. ids from nested objs

Yeah, you are right. We do ignore them for nested objects. I used this chance to remove the `cuid` package dependency since we already have a util method in the SDK.

**Pull request merged**
