### PR TITLE
RELEASE: 0.61.0

### PR DESCRIPTION
**Pull request by tyler-dunkel**
## Changes/solution

New services: 
* cognitiveServicesAccount
* recoveryVaults
* replicationAppliances
* replicationCenters
* replicationNetworks
* replicationPolicies
* synapseBigDataPools
* synapseSqlPools
* synapseWorkspaces

### CODE REVIEW

**Comment by csbrandt** [comment]
getting a schema issue

```
ℹ Validating Schema for version 10
✖ Schema validation failed
✖ 1 errors found in version 10 schema. Check the following lines in the schema.graphql file:
line 1671: Type azureCognitiveServicesAccount; Field application: inverse field cognitiveServicesAccounts doesn't exist for type azureADApplication.
✖ There was an issue pushing schema for providers: azure to dgraph at localhost:8997
ℹ undefined
✨  Done in 33.83s.
```

**Comment by tyler-dunkel** [comment]
> getting a schema issue
> 
> ```
> ℹ Validating Schema for version 10
> ✖ Schema validation failed
> ✖ 1 errors found in version 10 schema. Check the following lines in the schema.graphql file:
> line 1671: Type azureCognitiveServicesAccount; Field application: inverse field cognitiveServicesAccounts doesn't exist for type azureADApplication.
> ✖ There was an issue pushing schema for providers: azure to dgraph at localhost:8997
> ℹ undefined
> ✨  Done in 33.83s.
> ```

@hjaraujof please take a look at this. You can do the fixes directly on beta.

**Comment by tyler-dunkel** [comment]
@csbrandt @hjaraujof can you take a look at this release again and see if its good to go?

**Review by hjaraujof — APPROVED** [review]
LGTM. Manual test was OK

**Pull request merged**
